# Generated by Django 6.1.1 on 2026-09-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q_mail', '0002_remove_emailmessage_q_mail_emai_mailbox_90a6ee_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailboxinvestigation',
            name='is_cancellation_requested',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='mailboxinvestigation',
            name='last_heartbeat_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='mailboxinvestigation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Ingestion'), ('UPLOADING', 'Uploading PST File'), ('PROCESSING', 'Extracting & Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('STALLED', 'Stalled / Interrupted')], db_index=True, default='PENDING', max_length=32),
        ),
    ]
