# Generated by Django 6.1.1 on 2026-10-03 19:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntityRelationship',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relation_type', models.CharField(choices=[('EMAILED', 'Emailed / Communicated'), ('TRANSFERRED_FUNDS', 'Transferred Funds'), ('ISSUED_PO', 'Issued Purchase Order'), ('APPROVED_BY', 'Approved By'), ('SHARED_IDENTIFIER', 'Shared Identifier (Address/Phone/PAN)'), ('CONDUIT_TO', 'Pass-Through Conduit'), ('DIRECTOR_OF', 'Director / Beneficial Owner'), ('MENTIONED_IN', 'Mentioned in Evidence / Call'), ('ASSOCIATE', 'Known Associate / Co-Auditee')], db_index=True, default='ASSOCIATE', max_length=64)),
                ('confidence_score', models.FloatField(default=1.0, help_text='Confidence rating (0.0 to 1.0)')),
                ('weight', models.FloatField(default=1.0, help_text='Edge weight (e.g. monetary amount or interaction count)')),
                ('source_module', models.CharField(db_index=True, help_text='Originating tool (q_bank, q_trail, q_mail, q_ledger, etc.)', max_length=32)),
                ('is_direct', models.BooleanField(default=True, help_text='True for direct connection, False for multi-hop inferred')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Edge attributes (dates, channel, transaction IDs, etc.)')),
            ],
            options={
                'verbose_name': 'Entity Relationship',
                'verbose_name_plural': 'Entity Relationships',
                'ordering': ['-weight', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForensicEntity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('EMPLOYEE', 'Employee / Target Custodian'), ('VENDOR', 'Vendor / Supplier'), ('CUSTOMER', 'Customer / Client'), ('COMPANY', 'Company / Corporate Entity'), ('BANK_ACCOUNT', 'Bank Account'), ('EMAIL_ID', 'Email Address'), ('PHONE', 'Phone Number'), ('PO', 'Purchase Order'), ('INVOICE', 'Invoice'), ('DOCUMENT', 'Document / File'), ('UNKNOWN', 'Unclassified Entity')], db_index=True, default='UNKNOWN', max_length=32)),
                ('identifier', models.CharField(db_index=True, help_text='Normalized canonical identifier (e.g. EMAIL:foo@bar.com, ACC:HDFC:12345)', max_length=255, unique=True)),
                ('display_name', models.CharField(db_index=True, help_text='Human-readable label or entity name', max_length=255)),
                ('category', models.CharField(blank=True, default='General', help_text='Classification category (e.g. Individual, Corporate, Procurement)', max_length=64)),
                ('risk_rating', models.IntegerField(default=0, help_text='Calculated risk score (0-100)')),
                ('is_target', models.BooleanField(default=False, help_text='Whether this entity is a prime auditee/suspect')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Arbitrary entity metadata (attributes, tags, address, etc.)')),
            ],
            options={
                'verbose_name': 'Forensic Entity',
                'verbose_name_plural': 'Forensic Entities',
                'ordering': ['-risk_rating', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='EvidencePointer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_module', models.CharField(db_index=True, help_text='Originating forensic module name', max_length=32)),
                ('source_model', models.CharField(help_text='Model class name (e.g. BankTransaction, PurchaseOrder, EmailMessage)', max_length=64)),
                ('source_record_id', models.CharField(db_index=True, help_text='Primary key or reference identifier in originating table', max_length=128)),
                ('evidence_url', models.CharField(blank=True, default='', help_text='Clickable URL to inspect evidence in the primary tool', max_length=255)),
                ('summary_snippet', models.TextField(blank=True, default='', help_text='Human-readable evidence summary or finding text')),
                ('occurred_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the forensic event took place', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Raw payload or contextual snapshot from originating finding')),
                ('relationship', models.ForeignKey(help_text='Associated relationship edge', on_delete=django.db.models.deletion.CASCADE, related_name='evidence_pointers', to='q_link.entityrelationship')),
            ],
            options={
                'verbose_name': 'Evidence Pointer',
                'verbose_name_plural': 'Evidence Pointers',
                'ordering': ['-occurred_at', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='entityrelationship',
            name='source_entity',
            field=models.ForeignKey(help_text='Originating entity', on_delete=django.db.models.deletion.CASCADE, related_name='out_relations', to='q_link.forensicentity'),
        ),
        migrations.AddField(
            model_name='entityrelationship',
            name='target_entity',
            field=models.ForeignKey(help_text='Destination entity', on_delete=django.db.models.deletion.CASCADE, related_name='in_relations', to='q_link.forensicentity'),
        ),
        migrations.CreateModel(
            name='EntityAlias',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alias_name', models.CharField(db_index=True, help_text='Raw or variant name string', max_length=255)),
                ('match_source', models.CharField(choices=[('EXACT', 'Exact Key Match'), ('RAPIDFUZZ', 'Fuzzy Token Match'), ('LLM_INFERRED', 'LLM Semantic Inference'), ('MANUAL', 'Investigator Manual Link')], default='EXACT', max_length=32)),
                ('confidence', models.FloatField(default=1.0, help_text='Match confidence score (0.0 to 1.0)')),
                ('entity', models.ForeignKey(help_text='Associated master canonical entity', on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='q_link.forensicentity')),
            ],
            options={
                'verbose_name': 'Entity Alias',
                'verbose_name_plural': 'Entity Aliases',
                'ordering': ['-confidence', 'alias_name'],
            },
        ),
        migrations.CreateModel(
            name='ForensicTimelineEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_title', models.CharField(help_text="Brief headline (e.g. 'PO-2026-88 Issued', 'Transfer ₹5,00,000')", max_length=255)),
                ('event_description', models.TextField(blank=True, default='', help_text='Detailed description of the forensic interaction')),
                ('event_timestamp', models.DateTimeField(db_index=True, help_text='Exact date and time of the event')),
                ('source_module', models.CharField(db_index=True, help_text='Module reporting this event', max_length=32)),
                ('severity', models.CharField(default='INFO', help_text='Severity flag (INFO, WARNING, CRITICAL)', max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Contextual metadata for timeline playback')),
                ('entity', models.ForeignKey(help_text='Primary entity involved in this event', on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='q_link.forensicentity')),
                ('relationship', models.ForeignKey(blank=True, help_text='Optional linked relationship edge', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_events', to='q_link.entityrelationship')),
            ],
            options={
                'verbose_name': 'Forensic Timeline Event',
                'verbose_name_plural': 'Forensic Timeline Events',
                'ordering': ['event_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RelationshipAlert',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text="Alert headline (e.g. 'New Relationship: Vendor ABC connected to Employee X')", max_length=255)),
                ('alert_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, default='MEDIUM', max_length=16)),
                ('related_entities', models.JSONField(blank=True, default=list, help_text='Array of connected entity IDs, names, and roles')),
                ('risk_score', models.IntegerField(default=50, help_text='Calculated risk score (0-100)')),
                ('trigger_reason', models.TextField(blank=True, default='', help_text='Rule or threshold that triggered this alert')),
                ('ai_summary', models.TextField(blank=True, default='', help_text='LLM-synthesized narrative explaining the connection and investigative significance')),
                ('is_acknowledged', models.BooleanField(db_index=True, default=False, help_text='Whether an auditor has acknowledged this notification')),
                ('primary_entity', models.ForeignKey(help_text='Central entity triggering the alert', on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='q_link.forensicentity')),
            ],
            options={
                'verbose_name': 'Relationship Alert',
                'verbose_name_plural': 'Relationship Alerts',
                'ordering': ['-risk_score', '-created_at'],
            },
        ),
    ]
