# Generated by Django 6.1.1 on 2026-10-01 01:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvestigationProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(db_index=True, help_text='Target / Auditee Full Name', max_length=255)),
                ('employee_id', models.CharField(blank=True, db_index=True, default='', help_text='Employee ID or Case Reference', max_length=64)),
                ('department', models.CharField(blank=True, default='', help_text='Department / Division', max_length=128)),
                ('designation', models.CharField(blank=True, default='', help_text='Designation / Position', max_length=128)),
                ('email', models.EmailField(blank=True, default='', help_text='Official / Primary Email', max_length=254)),
                ('phone', models.CharField(blank=True, default='', help_text='Contact Phone', max_length=32)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active Investigation'), ('MONITORING', 'Under Monitoring'), ('CLEARED', 'Cleared / Closed'), ('FLAGGED', 'High Risk / Flagged')], db_index=True, default='ACTIVE', max_length=20)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk'), ('CRITICAL', 'Critical Risk')], default='MEDIUM', max_length=20)),
                ('notes', models.TextField(blank=True, default='', help_text='Investigative hypothesis, case background, or notes')),
                ('avatar_color', models.CharField(default='indigo', help_text='UI Accent color tag', max_length=32)),
            ],
            options={
                'verbose_name': 'Investigation Profile',
                'verbose_name_plural': 'Investigation Profiles',
                'ordering': ['full_name'],
            },
        ),
    ]
