# Generated by Django 6.1.1 on 2026-09-26 20:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScannedDevice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hostname', models.CharField(db_index=True, help_text='Endpoint Computer / Hostname', max_length=128)),
                ('scan_title', models.CharField(blank=True, default='', help_text='Investigation / Audit Label', max_length=255)),
                ('custodian_name', models.CharField(blank=True, default='', help_text='Assigned Custodian or User', max_length=255)),
                ('drive_letter', models.CharField(blank=True, default='', help_text='Target Root or Drive Letter (e.g., C:\\)', max_length=64)),
                ('file_system', models.CharField(blank=True, default='', help_text='File System (NTFS, FAT32, etc.)', max_length=32)),
                ('status', models.CharField(choices=[('COMPLETED', 'Scan Completed'), ('IN_PROGRESS', 'Scan In Progress'), ('PARTIAL', 'Partial / Interrupted'), ('IMPORTED', 'Evidence CSV Imported')], db_index=True, default='IMPORTED', max_length=32)),
                ('total_files_scanned', models.IntegerField(default=0)),
                ('total_matches_found', models.IntegerField(default=0)),
                ('total_bytes_scanned', models.BigIntegerField(default=0)),
                ('scan_completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Scanned Device',
                'verbose_name_plural': 'Scanned Devices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileEvidenceHit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_path', models.CharField(db_index=True, max_length=1024)),
                ('filename', models.CharField(db_index=True, max_length=255)),
                ('extension', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('matched_keyword', models.CharField(db_index=True, max_length=128)),
                ('match_type', models.CharField(choices=[('FILENAME', 'File Name Match'), ('CONTENT_TEXT', 'Text Content Match'), ('CONTENT_DOCX', 'Word Document Match'), ('CONTENT_XLSX', 'Excel Spreadsheet Match'), ('CONTENT_PPTX', 'PowerPoint Presentation Match'), ('CONTENT_ZIP_ENTRY', 'Zip Archive Entry Match'), ('CONTENT_ZIP_OFFICE', 'Zip Nested Document Match')], db_index=True, default='CONTENT_TEXT', max_length=64)),
                ('snippet', models.TextField(blank=True, default='', help_text='Surrounding text context snippet')),
                ('file_modified_at', models.DateTimeField(blank=True, null=True)),
                ('detection_timestamp', models.DateTimeField(blank=True, null=True)),
                ('risk_score', models.IntegerField(default=50, help_text='Calculated Risk Score (0-100)')),
                ('is_reviewed', models.BooleanField(default=False)),
                ('reviewer_notes', models.TextField(blank=True, default='')),
                ('device', models.ForeignKey(help_text='Originating Host / Device', on_delete=django.db.models.deletion.CASCADE, related_name='hits', to='q_scan.scanneddevice')),
            ],
            options={
                'verbose_name': 'File Evidence Hit',
                'verbose_name_plural': 'File Evidence Hits',
                'ordering': ['-risk_score', '-created_at'],
            },
        ),
    ]
