# Generated by Django 6.1.1 on 2026-09-30 15:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('po_number', models.CharField(db_index=True, max_length=64, unique=True)),
                ('po_date', models.DateTimeField(db_index=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('approved_by', models.CharField(blank=True, default='', max_length=128)),
                ('is_split_po', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VendorMaster',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vendor_code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('vendor_name', models.CharField(max_length=255)),
                ('gstin', models.CharField(blank=True, default='', max_length=32)),
                ('bank_account_no', models.CharField(blank=True, default='', max_length=64)),
                ('ifsc_code', models.CharField(blank=True, default='', max_length=32)),
                ('is_flagged', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ERPThreeWayMatch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=64)),
                ('grn_number', models.CharField(max_length=64)),
                ('po_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('grn_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('invoice_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('variance_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('has_anomaly', models.BooleanField(default=False)),
                ('anomaly_type', models.CharField(blank=True, default='', max_length=64)),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='q_ledger.purchaseorder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='q_ledger.vendormaster'),
        ),
    ]
