# Generated by Django 6.1.1 on 2026-09-30 17:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q_ledger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerDataset',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='SAP ERP Audit Dataset', max_length=255)),
                ('prpo_file', models.FileField(blank=True, null=True, upload_to='q_ledger/prpo/')),
                ('mara_file', models.FileField(blank=True, null=True, upload_to='q_ledger/mara/')),
                ('record_count', models.IntegerField(default=0)),
                ('total_spend', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
