# Generated by Django 6.1.1 on 2026-09-30 18:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q_ledger', '0002_ledgerdataset'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerMasterConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gl_file', models.FileField(blank=True, null=True, upload_to='q_ledger/masters/gl/')),
                ('sloc_file', models.FileField(blank=True, null=True, upload_to='q_ledger/masters/sloc/')),
                ('gl_account_count', models.IntegerField(default=0)),
                ('sloc_count', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
