# Generated by Django 6.1.1 on 2026-09-27 15:13

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_number', models.CharField(blank=True, db_index=True, default='', help_text='Account / Card Number', max_length=64)),
                ('bank_name', models.CharField(blank=True, default='', help_text='Financial Institution (e.g. HDFC, ICICI, SBI)', max_length=128)),
                ('account_holder', models.CharField(blank=True, default='', help_text='Primary Account Holder / Auditee', max_length=255)),
                ('statement_label', models.CharField(blank=True, default='', help_text='Audit Campaign Label', max_length=255)),
                ('source_filename', models.CharField(blank=True, default='', max_length=255)),
                ('currency', models.CharField(default='INR', max_length=8)),
                ('total_transactions', models.IntegerField(default=0)),
                ('total_debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('total_credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('cash_deposit_count', models.IntegerField(default=0)),
                ('hyundai_count', models.IntegerField(default=0)),
                ('high_risk_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active Audit'), ('COMPLETED', 'Audit Completed'), ('FLAGGED', 'High Risk / Flagged')], db_index=True, default='ACTIVE', max_length=32)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Bank Account Audit',
                'verbose_name_plural': 'Bank Account Audits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WatchlistRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_name', models.CharField(max_length=128)),
                ('keyword', models.CharField(db_index=True, max_length=128)),
                ('risk_weight', models.IntegerField(default=50)),
                ('category', models.CharField(default='General', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Watchlist Rule',
                'verbose_name_plural': 'Watchlist Rules',
                'ordering': ['-risk_weight', 'rule_name'],
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('txn_ref', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('txn_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('value_date', models.DateTimeField(blank=True, null=True)),
                ('narration', models.TextField(blank=True, default='', help_text='Raw bank transaction narration')),
                ('party_name', models.CharField(db_index=True, help_text='Extracted counterparty / tracking entity', max_length=255)),
                ('direction', models.CharField(choices=[('IN', 'Credit (Deposit)'), ('OUT', 'Debit (Withdrawal)')], db_index=True, default='OUT', max_length=8)),
                ('debit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('is_cash_deposit', models.BooleanField(db_index=True, default=False, help_text='CDM / Cash deposit')),
                ('is_hyundai_related', models.BooleanField(db_index=True, default=False, help_text='Hyundai entity match')),
                ('risk_score', models.IntegerField(db_index=True, default=0, help_text='Risk score (0-100)')),
                ('risk_level', models.CharField(choices=[('Low', 'Low Risk'), ('Medium', 'Medium Risk'), ('High', 'High Risk / Suspicious')], db_index=True, default='Low', max_length=16)),
                ('status', models.CharField(default='Cleared', max_length=32)),
                ('flag_reason', models.TextField(blank=True, default='')),
                ('account', models.ForeignKey(help_text='Originating Statement Account', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='q_bank.bankaccount')),
            ],
            options={
                'verbose_name': 'Bank Transaction',
                'verbose_name_plural': 'Bank Transactions',
                'ordering': ['-txn_date', '-created_at'],
            },
        ),
    ]
