# Generated by Django 6.1.1 on 2026-09-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q_bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='source_page',
            field=models.CharField(blank=True, default='', help_text='Source Page / Reference', max_length=64),
        ),
    ]
