# Generated by Django 6.1.1 on 2026-09-27 22:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q_bank', '0002_banktransaction_source_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditedPerson',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(db_index=True, help_text='Auditee / Person Full Name', max_length=255)),
                ('employee_id', models.CharField(blank=True, default='', help_text='Employee ID / Case Ref', max_length=64)),
                ('department', models.CharField(blank=True, default='', max_length=128)),
                ('designation', models.CharField(blank=True, default='', max_length=128)),
                ('pan_number', models.CharField(blank=True, default='', help_text='PAN / Tax ID', max_length=32)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Audited Person',
                'verbose_name_plural': 'Audited Persons',
                'ordering': ['full_name'],
            },
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='person',
            field=models.ForeignKey(blank=True, help_text='Associated Audited Person / Target Custodian', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='q_bank.auditedperson'),
        ),
    ]
