# Generated by Django 6.1.1 on 2026-09-28 00:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatChannel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('TEAMS', 'Microsoft Teams'), ('SLACK', 'Slack'), ('TELEGRAM', 'Telegram'), ('SMS', 'SMS / iMessage')], db_index=True, default='WHATSAPP', max_length=32)),
                ('channel_name', models.CharField(db_index=True, help_text='Channel Title or Contact Name', max_length=255)),
                ('custodian_name', models.CharField(blank=True, default='', help_text='Device Custodian / Auditee', max_length=255)),
                ('is_direct_message', models.BooleanField(default=False)),
                ('participant_count', models.IntegerField(default=2)),
                ('participants', models.JSONField(default=list, help_text='List of participant names/handles')),
                ('total_messages', models.IntegerField(default=0)),
                ('flagged_messages_count', models.IntegerField(default=0)),
                ('source_filename', models.CharField(blank=True, default='', max_length=255)),
                ('first_message_at', models.DateTimeField(blank=True, null=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('risk_score', models.IntegerField(db_index=True, default=0)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Chat Channel',
                'verbose_name_plural': 'Chat Channels',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatWatchlistRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_name', models.CharField(max_length=128)),
                ('keyword', models.CharField(db_index=True, max_length=128)),
                ('risk_weight', models.IntegerField(default=50)),
                ('category', models.CharField(default='Collusion', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Chat Watchlist Rule',
                'verbose_name_plural': 'Chat Watchlist Rules',
                'ordering': ['-risk_weight', 'rule_name'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_name', models.CharField(db_index=True, help_text='Sender Display Name', max_length=255)),
                ('sender_handle', models.CharField(blank=True, default='', help_text='Phone / Email / Username', max_length=128)),
                ('sent_at', models.DateTimeField(db_index=True)),
                ('message_text', models.TextField(blank=True, default='')),
                ('has_media', models.BooleanField(db_index=True, default=False)),
                ('media_type', models.CharField(choices=[('NONE', 'Text Only'), ('IMAGE', 'Image'), ('DOCUMENT', 'Document / PDF'), ('AUDIO', 'Voice Note / Audio'), ('VIDEO', 'Video')], default='NONE', max_length=16)),
                ('media_filename', models.CharField(blank=True, default='', max_length=255)),
                ('media_path', models.CharField(blank=True, default='', max_length=1024)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Message was deleted or retracted')),
                ('is_edited', models.BooleanField(default=False)),
                ('risk_score', models.IntegerField(db_index=True, default=0)),
                ('flagged_terms', models.JSONField(default=list)),
                ('reply_to_sender', models.CharField(blank=True, default='', max_length=255)),
                ('reply_to_text', models.TextField(blank=True, default='')),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('channel', models.ForeignKey(help_text='Originating Conversation Channel', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='q_chat.chatchannel')),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'ordering': ['sent_at', 'created_at'],
            },
        ),
    ]
