# Generated by Django 6.1.1 on 2026-09-26 18:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCase',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_ref', models.CharField(db_index=True, help_text='Case Reference Number', max_length=64, unique=True)),
                ('case_title', models.CharField(help_text='Investigation / Case Title', max_length=255)),
                ('custodian_name', models.CharField(help_text='Target Custodian / Auditee', max_length=255)),
                ('custodian_email', models.EmailField(blank=True, default='', max_length=255)),
                ('custodian_department', models.CharField(blank=True, default='', max_length=128)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Ingestion'), ('PROCESSING', 'Analyzing Documents'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=32)),
                ('total_documents', models.IntegerField(default=0)),
                ('authentic_count', models.IntegerField(default=0)),
                ('suspicious_count', models.IntegerField(default=0)),
                ('tampered_count', models.IntegerField(default=0)),
                ('average_authenticity_score', models.FloatField(default=100.0)),
            ],
            options={
                'verbose_name': 'Verification Case',
                'verbose_name_plural': 'Verification Cases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerifiedDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('mime_type', models.CharField(default='application/octet-stream', max_length=128)),
                ('file_extension', models.CharField(blank=True, default='', max_length=32)),
                ('sha256_hash', models.CharField(db_index=True, help_text='Evidence Hash', max_length=64)),
                ('storage_path', models.CharField(blank=True, default='', max_length=512)),
                ('file_created_at', models.DateTimeField(blank=True, null=True)),
                ('file_modified_at', models.DateTimeField(blank=True, null=True)),
                ('meta_created_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('meta_modified_at', models.DateTimeField(blank=True, null=True)),
                ('meta_author', models.CharField(blank=True, default='', max_length=255)),
                ('meta_creator', models.CharField(blank=True, default='', max_length=255)),
                ('meta_producer', models.CharField(blank=True, default='', max_length=255)),
                ('meta_software', models.CharField(blank=True, default='', max_length=255)),
                ('meta_company', models.CharField(blank=True, default='', max_length=255)),
                ('meta_title', models.CharField(blank=True, default='', max_length=512)),
                ('meta_subject', models.CharField(blank=True, default='', max_length=512)),
                ('incremental_updates_count', models.IntegerField(default=0)),
                ('editing_time_minutes', models.IntegerField(default=0)),
                ('revision_number', models.CharField(blank=True, default='', max_length=64)),
                ('authenticity_score', models.IntegerField(db_index=True, default=100, help_text='0 = Highly Tampered, 100 = Authentic')),
                ('risk_level', models.CharField(choices=[('AUTHENTIC', 'Authentic (Clean)'), ('SUSPICIOUS', 'Suspicious (Discrepancies)'), ('HIGH_RISK_TAMPERED', 'High Risk / Tampered')], db_index=True, default='AUTHENTIC', max_length=32)),
                ('has_timestamp_anomaly', models.BooleanField(db_index=True, default=False)),
                ('has_software_anomaly', models.BooleanField(db_index=True, default=False)),
                ('has_structural_anomaly', models.BooleanField(db_index=True, default=False)),
                ('anomalies', models.JSONField(default=list, help_text='List of detected anomaly flags')),
                ('raw_metadata', models.JSONField(default=dict, help_text='Complete extracted metadata tree')),
                ('summary', models.TextField(blank=True, default='')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='q_verify.verificationcase')),
            ],
            options={
                'verbose_name': 'Verified Document',
                'verbose_name_plural': 'Verified Documents',
                'ordering': ['authenticity_score', '-created_at'],
                'indexes': [models.Index(fields=['case', 'authenticity_score'], name='q_verify_ve_case_id_16c678_idx'), models.Index(fields=['case', 'risk_level'], name='q_verify_ve_case_id_c54c64_idx'), models.Index(fields=['case', 'mime_type'], name='q_verify_ve_case_id_f28e17_idx')],
            },
        ),
    ]
