# Generated by Django 6.1.1 on 2026-09-28 00:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioRecording',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('call_ref', models.CharField(db_index=True, help_text='Call Reference ID (e.g. CALL-2024-001)', max_length=64, unique=True)),
                ('call_title', models.CharField(db_index=True, help_text='Investigation Call Subject / Label', max_length=255)),
                ('custodian_name', models.CharField(blank=True, default='', help_text='Device Custodian / Target Auditee', max_length=255)),
                ('caller_number', models.CharField(blank=True, default='', max_length=64)),
                ('callee_number', models.CharField(blank=True, default='', max_length=64)),
                ('call_timestamp', models.DateTimeField(db_index=True)),
                ('duration_seconds', models.IntegerField(default=0, help_text='Audio Duration in Seconds')),
                ('audio_file_path', models.CharField(blank=True, default='', max_length=1024)),
                ('source_filename', models.CharField(blank=True, default='', max_length=255)),
                ('sha256_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('transcription_status', models.CharField(choices=[('COMPLETED', 'Transcription Completed'), ('PENDING', 'Pending Ingestion'), ('PROCESSING', 'Diarization In Progress'), ('FAILED', 'Transcription Failed')], db_index=True, default='COMPLETED', max_length=32)),
                ('total_segments', models.IntegerField(default=0)),
                ('flagged_segments_count', models.IntegerField(default=0)),
                ('risk_score', models.IntegerField(db_index=True, default=0)),
                ('detected_intent_summary', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Audio Recording',
                'verbose_name_plural': 'Audio Recordings',
                'ordering': ['-call_timestamp', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoiceWatchlistRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_name', models.CharField(max_length=128)),
                ('keyword', models.CharField(db_index=True, max_length=128)),
                ('risk_weight', models.IntegerField(default=50)),
                ('category', models.CharField(default='Collusion', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Voice Watchlist Rule',
                'verbose_name_plural': 'Voice Watchlist Rules',
                'ordering': ['-risk_weight', 'rule_name'],
            },
        ),
        migrations.CreateModel(
            name='TranscriptSegment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('speaker_tag', models.CharField(db_index=True, help_text='Speaker Tag / Identified Name', max_length=128)),
                ('start_time_seconds', models.FloatField(db_index=True)),
                ('end_time_seconds', models.FloatField()),
                ('text_content', models.TextField(help_text='Transcribed Spoken Text')),
                ('detected_intent', models.CharField(choices=[('General', 'General Conversation'), ('Price Negotiation', 'Price & Commercial Negotiation'), ('Collusion', 'Collusion / Kickback'), ('Pressure', 'Pressure / Coercion'), ('Concealment', 'Concealment / Off-the-Record'), ('Procurement', 'Tender / Bidding Discussion')], db_index=True, default='General', max_length=64)),
                ('flagged_keywords', models.JSONField(default=list)),
                ('confidence_score', models.FloatField(default=1.0)),
                ('risk_score', models.IntegerField(db_index=True, default=0)),
                ('recording', models.ForeignKey(help_text='Originating Audio Recording', on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='q_voice.audiorecording')),
            ],
            options={
                'verbose_name': 'Transcript Segment',
                'verbose_name_plural': 'Transcript Segments',
                'ordering': ['start_time_seconds', 'created_at'],
            },
        ),
    ]
