# Generated by Django 6.1.1 on 2026-09-30 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q_voice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiorecording',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='q_voice/recordings/'),
        ),
    ]
