# Generated by Django 6.1.1 on 2026-10-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q_voice', '0002_audiorecording_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiorecording',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
